### ISSUE TITLE
Building without cleaning, after increasing VERSION file contents, crashes the compiler

### ISSUE THREAD

**Issue by lagergren** [xtclang/xvm#115]

**Comment by lagergren** [comment]
This happened when Gene built everything, then changed VERSION and then did build. Then it ended up with a constant pool exception.

**Comment by lagergren** [comment]
We think this has to do with file renaming, for example the mack.x generating mack.xtc, which is then renamed to javatools_turtle.xtc before the build phase ends. This should appear as atomic to the rest of the world, but I would guess something gets in between there. 

Note that there could be a different reason. I haven't had time to do any investigation.

This is currently the only known place where you have to run a gradle clean as a workaround in the build.

**Comment by ggleyzer** [comment]
Fixed by [this commit ](https://github.com/xtclang/xvm/commit/538b718fafb448e08a6481a65abc84d73857d396)

**Comment by lagergren** [comment]
Nice! Now we have the beginning of a human readable archived thought process behind every line of code
