### ISSUE TITLE
The platform XTC plugin branch builds fine incrementally, except for resources not being picked up

### ISSUE THREAD

**Issue by lagergren** [xtclang/xvm#128]
Reproduce:

./gradlew build
./gradlew build (ensure that it uses everything in the cache, an performs no work)

- Edit the web server title in the vue file. 

./gradlew build (ensure it picks up the changes)
./gradlew build (ensure that it uses everything in the cache, an performs no work)

- Examine the xtc artifact that consumes the dist directory from the web app as a resource, and figure out why it doesn't get rebuilt properly.

**Comment by ggleyzer** [comment]
Fixed
