### ISSUE TITLE
Launchers should respect XDK_HOME

### ISSUE THREAD

**Issue by cpurdy** [xtclang/xvm#130]
**Is your feature request related to a problem? Please describe.**
`xec` and `xcc` (etc.) commands should use the XDK specified by `XDK_HOME`, iff that env variable exists.

**Describe the solution you'd like**
Launchers should check for the XDK_HOME env var (e.g. using `getenv()`).

**Describe alternatives you've considered**

* set path explicitly
* specify full path of the `xec` (etc.) commands on the command line
* copy the built libs into the location that already holds the XDK that's in the path (e.g. the way that we used to overwrite the brew install from the build 🤮)

**Additional context**
N/A

**Comment by lagergren** [comment]
The only thing that may be missing here (I don't know) is a way to make the launcher NOT respect XDK_HOME. You aren't always in a place where you can rewrite system variables, but it's no biggie. I just want to make it very easy for the user to understand what XDK is the "current" one.

**Comment by thegridman** [comment]
A number of other CLI type tools I use will pick up their home/config directory location from an environment variable (if set) but also have a corresponding command line flag to set the location too, which would be used in preference to any environment variable.

**Comment by cpurdy** [comment]
We can add the other suggested options later without a great deal of effort, if they are required.
