### ISSUE TITLE
Add ability to enable/disable auto-rebuild by `xec` command

### ISSUE THREAD

**Issue by cpurdy** [xtclang/xvm#131]
**Is your feature request related to a problem? Please describe.**
Command line execution always checks if a module rebuild is necessary, and does the rebuild automatically if the compiled module is out-of-date.

**Describe the solution you'd like**
Depending on whether the default is negative (don't auto rebuild) or positive (always check if rebuild is necessary and rebuild if necessary), the command line change could be something like:

* `xec --only ...` or `xec --norebuild ...` (if positive is the default)
* `xec --auto ...` (if negative is the default)

**Describe alternatives you've considered**
See above.

**Additional context**
Requested by Marcus.

**Comment by lagergren** [comment]
I think --no-rebuild=true can be added to the command line if the compiler may not be invoked by the runner. Otherwise default behaviour remains. 

(It may be more intuitive for an adopter to have it the other way around, but I'm not sure)
