### ISSUE TITLE
The installLocalDist layout, and the zip file contents layout no longer look like they should, after the "libexec" removal changes, that were merged before I had a chance to review them.

### ISSUE THREAD

**Issue by lagergren** [xtclang/xvm#135]
This what was in the zip in old pre-xtc plugin master:

/Users/marcus/Downloads/xdk
/Users/marcus/Downloads/xdk/bin
/Users/marcus/Downloads/xdk/bin/linux_launcher
/Users/marcus/Downloads/xdk/bin/macos_launcher
/Users/marcus/Downloads/xdk/bin/README.md
/Users/marcus/Downloads/xdk/bin/cfg_macos.sh
/Users/marcus/Downloads/xdk/bin/windows_launcher.exe
/Users/marcus/Downloads/xdk/bin/cfg_windows.cmd
/Users/marcus/Downloads/xdk/README.md
/Users/marcus/Downloads/xdk/examples
/Users/marcus/Downloads/xdk/examples/README.md
/Users/marcus/Downloads/xdk/examples/HelloWorld.x
/Users/marcus/Downloads/xdk/lib
/Users/marcus/Downloads/xdk/lib/collections.xtc
/Users/marcus/Downloads/xdk/lib/aggregate.xtc
/Users/marcus/Downloads/xdk/lib/jsondb.xtc
/Users/marcus/Downloads/xdk/lib/web.xtc
/Users/marcus/Downloads/xdk/lib/net.xtc
/Users/marcus/Downloads/xdk/lib/README.md
/Users/marcus/Downloads/xdk/lib/ecstasy.xtc
/Users/marcus/Downloads/xdk/lib/imdb.xtc
/Users/marcus/Downloads/xdk/lib/crypto.xtc
/Users/marcus/Downloads/xdk/lib/json.xtc
/Users/marcus/Downloads/xdk/lib/oodb.xtc
/Users/marcus/Downloads/xdk/doc
/Users/marcus/Downloads/xdk/doc/README.md
/Users/marcus/Downloads/xdk/javatools
/Users/marcus/Downloads/xdk/javatools/javatools.jar
/Users/marcus/Downloads/xdk/javatools/README.md
/Users/marcus/Downloads/xdk/javatools/javatools_turtle.xtc
/Users/marcus/Downloads/xdk/javatools/javatools_bridge.xtc

This is what is in current master: zip 

        0  02-16-2024 09:47   xdk-0.4.4/
       22  02-16-2024 09:41   xdk-0.4.4/VERSION
        0  02-16-2024 09:41   xdk-0.4.4/xdk/
        0  02-16-2024 09:41   xdk-0.4.4/xdk/bin/
     2049  02-16-2024 09:41   xdk-0.4.4/xdk/bin/README.md
     1458  02-16-2024 09:41   xdk-0.4.4/xdk/bin/cfg_macos.sh
      347  02-16-2024 09:41   xdk-0.4.4/xdk/bin/cfg_windows.cmd
     2612  02-16-2024 09:41   xdk-0.4.4/xdk/README.md
        0  02-16-2024 09:41   xdk-0.4.4/xdk/examples/
      759  02-16-2024 09:41   xdk-0.4.4/xdk/examples/HelloClient.x
      640  02-16-2024 09:41   xdk-0.4.4/xdk/examples/FizzBuzz.x
      108  02-16-2024 09:41   xdk-0.4.4/xdk/examples/README.md
     1257  02-16-2024 09:41   xdk-0.4.4/xdk/examples/HelloServer.x
     2833  02-16-2024 09:41   xdk-0.4.4/xdk/examples/https.p12
      457  02-16-2024 09:41   xdk-0.4.4/xdk/examples/HelloWorld.x
        0  02-16-2024 09:41   xdk-0.4.4/xdk/lib/
      135  02-16-2024 09:41   xdk-0.4.4/xdk/lib/README.md
        0  02-16-2024 09:41   xdk-0.4.4/xdk/doc/
       67  02-16-2024 09:41   xdk-0.4.4/xdk/doc/README.md
        0  02-16-2024 09:41   xdk-0.4.4/xdk/javatools/
      994  02-16-2024 09:41   xdk-0.4.4/xdk/javatools/README.md
        0  02-16-2024 09:47   xdk-0.4.4/bin/
    30832  02-16-2024 09:41   xdk-0.4.4/bin/linux_launcher
   118024  02-16-2024 09:41   xdk-0.4.4/bin/macos_launcher
   381894  02-16-2024 09:41   xdk-0.4.4/bin/windows_launcher.exe
        0  02-16-2024 09:47   xdk-0.4.4/lib/
  1734882  02-16-2024 09:41   xdk-0.4.4/lib/ecstasy.xtc
    17373  02-16-2024 09:41   xdk-0.4.4/lib/aggregate.xtc
    80561  02-16-2024 09:41   xdk-0.4.4/lib/collections.xtc
    25387  02-16-2024 09:41   xdk-0.4.4/lib/crypto.xtc
   247699  02-16-2024 09:41   xdk-0.4.4/lib/json.xtc
   486803  02-16-2024 09:41   xdk-0.4.4/lib/jsondb.xtc
   118869  02-16-2024 09:41   xdk-0.4.4/lib/net.xtc
    40976  02-16-2024 09:41   xdk-0.4.4/lib/oodb.xtc
   248970  02-16-2024 09:41   xdk-0.4.4/lib/web.xtc
    31124  02-16-2024 09:41   xdk-0.4.4/lib/webauth.xtc
   188047  02-16-2024 09:41   xdk-0.4.4/lib/xenia.xtc
        0  02-16-2024 09:47   xdk-0.4.4/javatools/
      474  02-16-2024 09:41   xdk-0.4.4/javatools/javatools_turtle.xtc
   164043  02-16-2024 09:41   xdk-0.4.4/javatools/javatools_bridge.xtc
  3428747  02-16-2024 09:41   xdk-0.4.4/javatools/javatools.jar

./gradlew installLocalDist is supposed to create a distribution layout similar to the one our installers place in the system, I guess, and that could also be installer dependent. I just to make sure that this is actually a working distribution.  And that it can be run, I don't necessarily car if it has a brew layout or not.  But this is what was intended, right? 

build/dist/
build/dist//bin
build/dist//bin/xcc
build/dist//bin/linux_launcher
build/dist//bin/macos_launcher
build/dist//bin/xec
build/dist//bin/windows_launcher.exe
build/dist//bin/xtc
build/dist//xdk
build/dist//xdk/bin
build/dist//xdk/bin/README.md
build/dist//xdk/bin/cfg_macos.sh
build/dist//xdk/bin/cfg_windows.cmd
build/dist//xdk/README.md
build/dist//xdk/examples
build/dist//xdk/examples/HelloClient.x
build/dist//xdk/examples/FizzBuzz.x
build/dist//xdk/examples/README.md
build/dist//xdk/examples/HelloServer.x
build/dist//xdk/examples/https.p12
build/dist//xdk/examples/HelloWorld.x
build/dist//xdk/lib
build/dist//xdk/lib/README.md
build/dist//xdk/doc
build/dist//xdk/doc/README.md
build/dist//xdk/javatools
build/dist//xdk/javatools/README.md
build/dist//VERSION
build/dist//lib
build/dist//lib/collections.xtc
build/dist//lib/webauth.xtc
build/dist//lib/aggregate.xtc
build/dist//lib/jsondb.xtc
build/dist//lib/web.xtc
build/dist//lib/net.xtc
build/dist//lib/ecstasy.xtc
build/dist//lib/crypto.xtc
build/dist//lib/xenia.xtc
build/dist//lib/json.xtc
build/dist//lib/oodb.xtc
build/dist//javatools
build/dist//javatools/javatools.jar
build/dist//javatools/javatools_turtle.xtc
build/dist//javatools/javatools_bridge.xtc

**Comment by cpurdy** [comment]
This is the correct layout for the "xdk result" in the build and/or dist:

```

xdk
├── README.md
├── bin
│   ├── README.md
│   ├── cfg_macos.sh
│   ├── cfg_windows.cmd
│   ├── linux_launcher
│   ├── macos_launcher
│   └── windows_launcher.exe
├── doc
│   └── README.md
├── examples
│   ├── FizzBuzz.x
│   ├── HelloClient.x
│   ├── HelloServer.x
│   ├── HelloWorld.x
│   ├── README.md
│   └── https.p12
├── javatools
│   ├── README.md
│   ├── javatools.jar
│   ├── javatools_bridge.xtc
│   └── javatools_turtle.xtc
└── lib
    ├── README.md
    ├── aggregate.xtc
    ├── collections.xtc
    ├── crypto.xtc
    ├── ecstasy.xtc
    ├── json.xtc
    ├── jsondb.xtc
    ├── net.xtc
    ├── oodb.xtc
    ├── web.xtc
    ├── webauth.xtc
    └── xenia.xtc
```

**Comment by cpurdy** [comment]
The only reason "libexec" existed was because `brew` mandates it. And the only place that `./libexec/` ever showed up was in the build for the two brew-related projects and in the results of doing a brew install of one of those projects' outputs. This is what it looks like inside brew:

```
/opt/homebrew/Cellar/xdk-latest
└── 0.4.3.934
    ├── INSTALL_RECEIPT.json
    ├── README.md
    ├── bin
    │   ├── xcc -> ../libexec/bin/macos_launcher
    │   ├── xec -> ../libexec/bin/macos_launcher
    │   └── xtc -> ../libexec/bin/macos_launcher
    └── libexec
        ├── bin
        │   ├── README.md
        │   ├── cfg_macos.sh
        │   ├── cfg_windows.cmd
        │   ├── linux_launcher
        │   ├── macos_launcher
        │   ├── windows_launcher.exe
        │   ├── xec
        │   └── xtc
        ├── doc
        │   └── README.md
        ├── examples
        │   ├── FizzBuzz.x
        │   ├── HelloClient.x
        │   ├── HelloServer.x
        │   ├── HelloWorld.x
        │   ├── README.md
        │   └── https.p12
        ├── javatools
        │   ├── README.md
        │   ├── javatools.jar
        │   ├── javatools_bridge.xtc
        │   └── javatools_turtle.xtc
        └── lib
            ├── README.md
            ├── aggregate.xtc
            ├── collections.xtc
            ├── crypto.xtc
            ├── ecstasy.xtc
            ├── json.xtc
            ├── jsondb.xtc
            ├── net.xtc
            ├── oodb.xtc
            ├── web.xtc
            ├── webauth.xtc
            └── xenia.xtc
```

Here's the `xdk-latest` brew install (one of the two brew installs that I created):

```
class XdkLatest < Formula
  desc "Ecstasy Development Kit (XDK)"
  homepage "https://github.com/xtclang/xvm/"
  url "http://xtclang.org/downloads/xdk-0.4.3ci915+b01a998dd0f4e5c7b01684d83671c3c48add147c.tar.gz"
  version "0.4.3.915"
  sha256 "c8df6b6e8bf6634dcb2bedc8a469899eddfda2ad590ed1f878cc893d50c83ad0"
  license "Apache-2.0"

  depends_on "openjdk"

  def install
    libexec.mkpath
    cp_r Dir[buildpath/"*"], libexec
    osname = OS.linux? ? "linux" : "macos"
    bin.install_symlink "#{libexec}/bin/#{osname}_launcher" => "xec"
    bin.install_symlink "#{libexec}/bin/#{osname}_launcher" => "xtc"
    bin.install_symlink "#{libexec}/bin/#{osname}_launcher" => "xcc"
  end

  test do
    assert shell_output("xec", 255).include? "Error: Module file required"
  end
end
```

Long story short: It downloads the zip, creates a "libexec" dir under where brew tells it to install, and then copies the contents of the zip to that libexec dir. And I had to do that because if I didn't, they (the Homebrew project) would reject the brew recipe. Because they have lots of rules, for good historical (if not design) reasons, and I'm not about to question them.
