### ISSUE TITLE
Rename UnsupportedOperation to Unsupported

### ISSUE THREAD

**Issue by cpurdy** [xtclang/xvm#140]
**Describe the bug**
Exception names describe what went wrong, attempting to use nouns and avoiding ending the name with "Exception". There are of course exceptions to this rule, but we try to reduce them when possible.

In this case, we have the following usage:

```
throw new UnsupportedOperation();
```

While this is definitely better than `UnsupportedOperationException`, the problem that we're trying to describe is that something is _unsupported_, and "operation" doesn't add any quality information.

**To Reproduce**
n/a

**Expected behavior**
The result of this change will be code like:

```
throw new Unsupported();
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by lagergren** [comment]
That's while you typically send a string as an argument, or getClass().getSimpleName() or something like that?

**Comment by lagergren** [comment]
To check alternatives in other ecosystems, the Kotlin TODO("...") is one example. Or its assert(condition) { lambda }

**Comment by cpurdy** [comment]
I was unaware that Kotlin had a TODO. Just looked it up: It's a function that throws.

Ecstasy has had a `TODO` keyword (it's an expression, but it's normally used as a statement) since day one. e.g.

```
@Override
SimpleRequest with(Uri?        uri      = Null,
                   Protocol?   protocol = Null,
                   Path?       path     = Null,
                   AcceptList? accepts  = Null,
                   ) {
    TODO CP
}
```

... and ...

```
...
} else {
    TODO("delineation of non-delineated data");
}
```

... and ...

```
if (!(defaultHasher := algorithms.hasherFor("MD5"))) {
    defaultHasher = TODO create crypto.hashers.MD5 class
}
```

**Comment by cpurdy** [comment]
Ecstasy also has an assert flavor of `TODO`:

```
assert:TODO format <= Huge as "Someone needs to implement the Huge format";
```

(And of course you can just throw the exception yourself.)

**Comment by cpurdy** [comment]
> That's while you typically send a string as an argument, or getClass().getSimpleName() or something like that?

Two issues here:

1) the name is too long for no good reason (other than influence from e.g. Java)
2) yes! we definitely would pass a descriptive string if appropriate

**Comment by lagergren** [comment]
In Java, the naming conventions for Throwables as per the code standard are that they end with Exception or Error, and some linters will warn about that. I guess we don’t have any such conventions.  Perhaps the case of unsupported is more similar to the Kotlin TODO than the Java throw new UnsupportedOperationException(x)

**Comment by cpurdy** [comment]
No, we don't have any such conventions. We try to *not* end our exception names with "Exception", although there are exceptions to that rule 🤣

Exceptions are non-overlapping with other types, in that you can't catch or throw an `Int` or a `List` (i.e. it has to be an exception), and you generally only instantiate an exception at the point at which it is being thrown. So adding Exception to the end of the name is only acceptable if you also add `FactoryBuilderFactory`.

Q: "So what's the problem, officer?"
A: "Well, it's an IllegalState."

Not an IllegalStateException. IllegalState is raised, and it _is an_ exception. The result reads way better, and doesn't include useless redundant information. (We did begin the design with "Exception" tacked onto the end of everything ... old habits die hard.)

In the end, the change I submitted uses `Unsupported` as the catch-all for this category, and `NotImplemented` is a specific sub-class used by the `TODO` keyword and the `assert:TODO` statement.
