### ISSUE TITLE
Fix a java.lang.ClassCastException

### ISSUE THREAD

**Issue by dimitrirakitine** [xtclang/xvm#145]
java.lang.ClassCastException: class org.xvm.runtime.ObjectHandle$InitializingHandle cannot be cast to class org.xvm.runtime.template.xEnum$EnumHandle (org.xvm.runtime.ObjectHandle$InitializingHandle and org.xvm.runtime.template.xEnum$EnumHandle are in unnamed module of loader 'app')
	at org.xvm.runtime.template.xEnum.createConstHandle(xEnum.java:102)
	at org.xvm.runtime.Utils.constructSingletonHandle(Utils.java:710)
	at org.xvm.runtime.Utils$1.process(Utils.java:630)
	at org.xvm.runtime.ServiceContext.execute(ServiceContext.java:659)
	at org.xvm.runtime.ServiceContext.drainWork(ServiceContext.java:383)
	at org.xvm.runtime.ServiceContext.execute(ServiceContext.java:433)
	at org.xvm.runtime.Container.lambda$schedule$0(Container.java:161)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

	at ^ecstasy.xtclang.org (ConstructSingleton: Class{class=ecstasy:reflect.ParameterTemplate.Category.DefaultParameter, package=ecstasy:reflect, module=ecstasy.xtclang.org})
	    =========
	at reflect.RTMethodTemplate.parameters.get() (RTMethodTemplate.x:27)
	at reflect.Type.createHasher().isImplemented(String, Int) (Type.x:952)
	at reflect.Type.createHasher() (Type.x:964)
	at reflect.RTType.hasher.calc() (RTType.x:71)
	at annotations.LazyVar.get() (LazyVar.x:41)
	at reflect.RTType.hashed() (RTType.x:62)
	at collections.HashMap.construct(Int) (HashMap.x:23)
	at collections.HashSet.construct(Int) (HashSet.x:16)
	at reflect.TypeSystem.construct(Array<Module>, Array<Boolean>, Set<String>) (TypeSystem.x:29)
	at reflect.Class.displayName.get() (Class.x:156)
	at reflect.Class.estimateStringLength() (Class.x:590)
	at Object.toString() (Object.x:33)
	at Object.toString() (Object.x:39)
	at BOuter.InnerC.foo() (nesting.x:23)
	at BOuter.bar() (nesting.x:18)
	at testSimple() (nesting.x:11)
	at run() (nesting.x:5)
	at ^TestNesting (run())
	    =========
	at mgmt.Container.invoke(String, Tuple, Nullable | Service)

**Comment by ggleyzer** [comment]
What is the test scenario?

**Comment by dimitrirakitine** [comment]
just nesting.x

**Comment by dimitrirakitine** [comment]
just run /Users/dima/xvm/xvm/manualTests/src/main/x/nesting.x

**Comment by ggleyzer** [comment]
I cannot reproduce:
```

manualTests$ xec nesting.x        

** testSimple()
inner foo of B; this=BOuter.InnerC
inner foo of D; this=DOuter.InnerC
inner foo of B; this=BOuter.InnerC

** testInsane()
PB.M.foo() this=PB.C
PB.C.foo() this=PB.C
PB.A.foo() this=PB.C
DC.P.C.foo() this=DC.P.C
PB.M.foo() this=DC.P.C
PB.C.foo() this=DC.P.C
DC.P.A.foo() this=DC.P.C
BI.P.A.foo() this=DC.P.C
manualTests$ 
```

**Comment by ggleyzer** [comment]
Or with gradle:
```
xvm$ ./gradlew :manualTests:runOne -PtestName=nesting

> Task :manualTests:runOne
[manualTests:runOne] Resolving modules to run from module path: '[/Users/ggleyzer/Development/xvm/manualTests/build/xtc/main/lib, /Users/ggleyzer/Development/xvm/manualTests/build/xtc/xdk/lib]'
[manualTests:runOne] Task local module configuration is present, overriding extension configuration.
[manualTests] JavaExec command (launcher JavaExecLauncher): java -showversion -cp /Users/ggleyzer/Development/xvm/manualTests/build/xtc/xdk/lib/javatools.jar org.xvm.tool.Runner --verbose -L /Users/ggleyzer/Development/xvm/manualTests/build/xtc/main/lib -L /Users/ggleyzer/Development/xvm/manualTests/build/xtc/xdk/lib nesting
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Zulu21.30+15-CA (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu21.30+15-CA (build 21.0.1+12-LTS, mixed mode, sharing)
Info: JVM version: 21.0.1+12-LTS

Options
    {
    -v
    -L:
       [0]=/Users/ggleyzer/Development/xvm/manualTests/build/xtc/main/lib
       [1]=/Users/ggleyzer/Development/xvm/manualTests/build/xtc/xdk/lib
    Target(s)=nesting (/Users/ggleyzer/Development/xvm/manualTests/nesting)
    }

Info: Executing "TestNesting" from /Users/ggleyzer/Development/xvm/manualTests/build/nesting.xtc

** testSimple()
inner foo of B; this=BOuter.InnerC
inner foo of D; this=DOuter.InnerC
inner foo of B; this=BOuter.InnerC

** testInsane()
PB.M.foo() this=PB.C
PB.C.foo() this=PB.C
PB.A.foo() this=PB.C
DC.P.C.foo() this=DC.P.C
PB.M.foo() this=DC.P.C
PB.C.foo() this=DC.P.C
DC.P.A.foo() this=DC.P.C
BI.P.A.foo() this=DC.P.C

[manualTests:runOne] ( 1/ 1)   nesting [DefaultXtcRunModule_Decorated: moduleName='nesting', methodName='run', moduleArgs='[]']
[manualTests:runOne] ( 1/ 1)       SUCCESS XtcExecResult: [exitValue=0, SUCCESS (no failure object)]

BUILD SUCCESSFUL in 3s
71 actionable tasks: 4 executed, 67 up-to-date
xvm$ 
```

**Comment by dimitrirakitine** [comment]
it fails in IntelliJ

**Comment by ggleyzer** [comment]
I wonder if your `manualTests/build/xtc/xdk/lib` is out-of-date. Can you please try from 'xvm' directory:
```
./gradlew :manualTests:clean
./gradlew :manualTests:build
```

**Comment by ggleyzer** [comment]
```
/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home/bin/java -Xms1024m -Xmx1024m -ea -Dxvm.parallelism=1 -javaagent:/Applications/Dev/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=59623:/Applications/Dev/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /Users/ggleyzer/Development/xvm/javatools/out/production/classes:/Users/ggleyzer/Development/xvm/javatools/out/production/resources:/Users/ggleyzer/Development/xvm/javatools_utils/out/production/classes org.xvm.tool.Runner -o build/xtc/main/lib -L build/xtc/main/lib -L ../build/dist/lib -L ../build/dist/javatools src/main/x/nesting.x

** testSimple()
inner foo of B; this=BOuter.InnerC
inner foo of D; this=DOuter.InnerC
inner foo of B; this=BOuter.InnerC

** testInsane()
PB.M.foo() this=PB.C
PB.C.foo() this=PB.C
PB.A.foo() this=PB.C
DC.P.C.foo() this=DC.P.C
PB.M.foo() this=DC.P.C
PB.C.foo() this=DC.P.C
DC.P.A.foo() this=DC.P.C
BI.P.A.foo() this=DC.P.C

Process finished with exit code 0
```

**Comment by dimitrirakitine** [comment]
ah clicked on reload gradle projects again and it works now. on first click it failed, but second click fixed it. magically

**Comment by ggleyzer** [comment]
Hmm... very concerning. I'm afraid it's a timing issue, though I cannot figure out how

**Comment by dimitrirakitine** [comment]
sounds like old good weblogic class loaders casting error. anyway, reloading all gradle projects again fixed it

**Comment by ggleyzer** [comment]
I'm still afraid it's my bug; please keep an eye. If that happens again, would be very helpful to debug it on your machine

**Comment by cpurdy** [comment]
> I always do git pull, ./gradlew build, click on reload in IntelliJ and run. this time second reload in IntelliJ was required

Remember to do ./gradlew clean before ./gradlew build

**Comment by dimitrirakitine** [comment]
lately it is git and gradle support forum. as far as I can remember clean is not recommended.

**Comment by dimitrirakitine** [comment]
this fails with a brand new build

java -jar ../manualTests/build/xtc/xdk/lib/javatools.jar xec ../manualTests/src/main/x/EchoTest.x 
Exception in thread "main" java.lang.ClassCastException: class java.util.Collections$EmptyList cannot be cast to class java.util.ArrayList (java.util.Collections$EmptyList and java.util.ArrayList are in module java.base of loader 'bootstrap')
	at org.xvm.tool.Runner.process(Runner.java:247)
	at org.xvm.tool.Launcher.run(Launcher.java:147)
	at org.xvm.tool.Runner.launch(Runner.java:70)
	at org.xvm.tool.Runner.main(Runner.java:61)
	at org.xvm.tool.Launcher.main(Launcher.java:99)

**Comment by dimitrirakitine** [comment]
ah yes this cast
ArrayList<File> libPath = (ArrayList<File>) options.getModulePath();
is wrong
java -jar ../manualTests/build/xtc/xdk/lib/javatools.jar xec -L ../manualTests/build/xtc/xdk/lib   ../manualTests/src/main/x/EchoTest.x
works

**Comment by lagergren** [comment]
@dimitrirakitine Why would the command you sent me work? You don't have the XDK on the module path.  Can we try to keep separate issues in separate GitHub requests?

@cpurdy @ggleyzer Why are we hard-casting options.getModulePath() to an Array list? The API (as it very much should), returns a List<String> from getModulePath(). 

Taking a look at Runner.process, I notice that it's a very long method, and it would be great if you could split out its processing burden into smaller private methods. 

The code also does several strange things. Starting at line 239 in the "process" method:

* While you create a new ArrayList under if (fcompile) block, the storage type should be List<String>, not ArrayList<String>, to preserve abstraction of the compiler args collections. (Or when it's obvious on the right side what type is created, you may even do var compilerArgs = new ArrayList<>(). It's perfectly clear that you are putting an ArrayList into compiler args.

* Then, on line 247, you ask for the module path, List<File> by declaration, and force cast to to an ArrayList, assuming implementation knowledge about the getModulePath representation. This doesn't work. In some cases it's an emptyList, which certainly is not implemented as an ArrayList. 

* On line 248 you check if the returned list is not empty, in which case you loop through its elements. This is redundant.

In general, the code base has a lot of collection based APIs, and this is not the only place where you only use the Java collections API, but still cast stuff to their implementation type. We have a lot of casts in the Java code base, which is a bit of a warning sign, since that normally builds up to code smells in an object oriented language.

**Comment by ggleyzer** [comment]
[Fixed here](https://github.com/xtclang/xvm/commit/83aae104bbf5abdd3c723897bba9bcb512d5a470). Thanks, Dima!
