### ISSUE TITLE
Failure to report a parsing error

### ISSUE THREAD

**Issue by ggleyzer** [xtclang/xvm#191]
Consider a very simple code:

    Int i = 42;
    console.print($"{i)}”);
    //                ^ a non-matching right parenthesis

It should not compile, but it does.

**Comment by cpurdy** [comment]
I get a compiler error:

```
Error: /Users/cameron/Development/xvm/manualTests/src/main/x/test.x (test.x:5) [5:23..5:32] LEXER-08: An illegally terminated string literal: "{0}". ("$\"{i)}”);")
Error: /Users/cameron/Development/xvm/manualTests/src/main/x/test.x (test.x:5) [5:32] PARSER-03: Expected token ")"; found "}".

```

**Comment by ggleyzer** [comment]
I think what happens is that the text editor here replaces the double quotes with other double quotes.
Instead of copying, just type it and you'll see that compiler doesn't complain.

**Comment by ggleyzer** [comment]
Maybe we need to treat both double quotes in the same way?
```    
    Int i = 42;
    console.print($"{i)=}");
```
vs.
```
   Int i = 42;
   console.print($”{i)=}”);
```
