### ISSUE TITLE
Latest build pulled with brew fails to compile

### ISSUE THREAD

**Issue by Boardmad** [xtclang/xvm#237]
gradle clean build produces
Error: /Users/xtclang/Development/platform/common/src/main/x/common/AccountManager.x:9 [9:1..9:35] COMPILER-36: Could not find name "HashInfo" within "Class{class=web:security.Realm, package=web:security, module=web.xtclang.org}". ("import web.security.Realm.HashInfo")
Error: /Users/xtclang/Development/platform/common/src/main/x/common/WebHost.x:13 [13:1..13:25] COMPILER-36: Could not find name "HostInfo" within "Package{package=web:http, module=web.xtclang.org}". ("import web.http.HostInfo")
Error: /Users/xtclang/Development/platform/common/src/main/x/common/WebHost.x:16 [16:1..16:39] COMPILER-36: Could not find name "CatalogExtras" within "Class{class=xenia:HttpHandler, module=xenia.xtclang.org}". ("import xenia.HttpHandler.CatalogExtras")

**To Reproduce**
follow xtclang intro guidance
directories, redirects for localhost, clone local install, npm install, gradle clean build fails

**Expected behavior**
Build should complete and allow login to local paas

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.4
 - Browser: Chrome
 
**Smartphone (please complete the following information):**
 n/a

**Comment by ggleyzer** [comment]
My bad; failed to respond on time. Long fixed since :)

**Comment by Boardmad** [comment]
Morning Glenn
Just revisiting the build and I'm still getting the same errors namely 
"Error: /Users/compator/Development/platform/common/src/main/x/common/AccountManager.x:9 [9:1..9:35] COMPILER-36: Could not find name "HashInfo" within "Class{class=web:security.Realm, package=web:security, module=web.xtclang.org}". ("import web.security.Realm.HashInfo")
Error: /Users/compator/Development/platform/common/src/main/x/common/WebHost.x:14 [14:1..14:25] COMPILER-36: Could not find name "HostInfo" within "Package{package=web:http, module=web.xtclang.org}". ("import web.http.HostInfo")
Error: /Users/compator/Development/platform/common/src/main/x/common/WebHost.x:17 [17:1..17:39] COMPILER-36: Could not find name "CatalogExtras" within "Class{class=xenia:HttpHandler, module=xenia.xtclang.org}". ("import xenia.HttpHandler.CatalogExtras")

I'm now also receiving a "Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0."
Which resolves to 
"[warn]  The Project.exec(Action) method has been deprecated.
This is scheduled to be removed in Gradle 9.0.
        - Solutions
[enum]  Use ExecOperations.exec(Action) or ProviderFactory.exec(Action) instead.
 
 Possibly related but I initially ran the 'get started' at xqizit.com and on trying to compile the HelloServer.x I received the following
 Error: /Users/compator/xtclang/webserver/HelloServer.x:22 [22:9..22:72] COMPILER-56: Could not find a matching method or function "createServer" for type "HelloServer:xenia". ("xenia.createServer(this, new HostInfo(\"localhost\", 8080, 8090))")
Error: /Users/compator/xtclang/webserver/HelloServer.x:22 [22:34..22:71] COMPILER-38: Name "HostInfo" is unresolvable. ("new HostInfo(\"localhost\", 8080, 8090)")

I've installed and verified the build is there and both 'xec' and 'xcc' work fine in the terminal!

Any help appreciated sir !
S

**Comment by ggleyzer** [comment]
It appears that our publishing to brew is not working atm. I would suggest cloning our xvm repo and building the Ecstasy libraries using `./gradlew installDist` command.

**Comment by ggleyzer** [comment]
If you'd like, I can set up a zoom session to help you set up and get the platform running

**Comment by Boardmad** [comment]
That would be super many thanks Gene...let me know when works best for you as I know we're a few hours out of kilter !

**Comment by ggleyzer** [comment]
On top of that, I'm in LA right now for a couple of days :) I will have some time in about an hour - would 9:10 PST work for you?

**Comment by Boardmad** [comment]
HAH ! Awesome...yep works for me ! I make that 17:10 GMT. Shoot me a zoom innvite and I'll see you then Gene

**Comment by ggleyzer** [comment]
[Ready when you are](https://us02web.zoom.us/j/81479970744?pwd=WXpTUlFtdzhXTEdvdnJrTkZNNHRhdz09)

**Comment by Boardmad** [comment]
Hi Gene
Come back to get the platform built and tested and getting this when issuing gradle clean build in the /development/platform directory

Error: Cannot find module '/Users/compator/Development/platform/platformUI/gui/node_modules/quasar/dist/transforms/import-transformation.js'

And this file is indeed missing from the filesystem?

**Comment by Boardmad** [comment]
compator@compator-mac ~ % node --version
v23.3.0
compator@compator-mac ~ % quasar --version
@quasar/cli v2.4.1
compator@compator-mac ~ % 

So I'm ahead of you on node and quasar cli and have nothing for quasar/app-vite?  This repo was cloned this afternoon about 14:30 weird I have different dependencies?

**Comment by ggleyzer** [comment]
Just in case - I'll email you my package-lock.json. It shows all the module versions I'm currently using

**Comment by Boardmad** [comment]
Would you do me a favour and send me your package.json for comparison too please Gene? I did a diff on the package-lock.json you sent and there's quite a bit of drift between yours and what's getting pulled after the platform setup guidance?

**Comment by ggleyzer** [comment]
My package.json is checked it, so it's exactly the repo version. Hasn't changed in six months

**Comment by Boardmad** [comment]
So it's a hangover from the build challenge then as I pulled the latest repo from Git?
  
​
  
​Anyway your package-lock worked so I'll work from that going forward
  
​
  
​Cheers
  
​S
  
​

**Comment by lagergren** [comment]
I assume that package-lock.json should be under source control, like e.g. a frozen requirements.txt file in Python.  

There is an ancient branch where I have started to move the platform build to gradle, using the node plugins and stuff, but due to various family emergencies, I am afraid I haven't had time to update and merge that yet.  Anyway, it is possible with some gradle work to use built in mechanisms for node / npm builds etc, to get things work out of the box for newer versions. I will get there eventually. We do want a build without any installation requirements apart from ./gradlew.

**Comment by cpurdy** [comment]
Just be careful about that assumption, and double check how other projects do it. I know that Gene and I had issues previously with the `package-lock.json` file screwing things up, so it may be one of those kryptonite files that must **not** be in source control. Definitely worth checking best practices for.

FWIW there are hundreds of threads on the topic on StackOverflow etc. e.g. "Yes, package-lock.json is intended to be checked into source control" and lots of other good comments: https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by cpurdy** [comment]
And this is definitely not an AI written 🤣 article: https://codefinity.com/blog/Should-I-Commit-package-lock.json

**Comment by lagergren** [comment]
It's definitely made to be checked in. This is a well documented design decision. The only problem I have seen with frozen npm requirements is that some horror-security thing gets the full version pulled - in which case it needs to be updated.  Normally, keeping the packages frozen under source control is the only guarantee you have for deterministic bits, but I have only used the (same) mechanism extensively in python and rust. In the Maven echo system, you usually get by with specific artifact versions for everything, some times with added version constraint ranges.

**Comment by Boardmad** [comment]
Yep understood Marcus and all I can say is that from a clean pull from the repo, run the guide, fail the build, replace package-lock.json with Gene's then rebuild successfully, compile and then "xec -L lib/ lib/kernel.xtc" I'm a bit stymied! Nevertheless the fundamental issue I had is fixed, so we persevere !

**Comment by lagergren** [comment]
Thank you! 

Glad to hear it worked. 

Btw - if you have some skills in the build/gradle/github actions/ci/cd area, there is currently some low hanging fruit in several places. Any contribution request, no matter how small, is of course welcome! I hope to finally get some contiguous time to address release, build and artifact distribution issue in 2-3 weeks. It’s not “hard” just a lot of small things that are irritating to debug.  We also want to do further language support, but having a decent dev infra in place is definitely priority one so that people can start experimenting easily, and do their own xtc projects with gradle build files and so on…

&M
