### ISSUE TITLE
Collections are broken

### ISSUE THREAD

**Issue by thegridman** [xtclang/xvm#79]
The recent changes to collections filtering has broken something.

Here is a reproducer which used to work.
```
module collection_bug {

    void run() {
        Callback[] Callbacks = new Array();
        Callbacks.add(new MyCallbackOne());
        Callbacks.add(new MyCallbackTwo());

        for (Callback Callback : Callbacks.filter(c -> !c.is(MyCallbackOne))) {
            Callback.call();
        }
    }

    interface Callback {
        void call();
    }

    const MyCallbackOne
            implements Callback {
        @Override
        void call() {
        }
    }

    const MyCallbackTwo
            implements Callback {
        @Override
        void call() {
        }
    }
}
```

It fails with 
```
2023-06-27 21:53:22.962 Service "collection_bug" (id=1) at ^collection_bug (CallLaterRequest: native), fiber 1: Unhandled exception: ecstasy:TypeMismatch: ecstasy:collections.deferred.FilteredCollection<collection_bug:Callback>
	at collections.Collection.filter(Type<Collection<Collection.Element>>, function Boolean(Collection.Element), Nullable | ecstasy:collections.Aggregator<Collection.Element, filter(?)#Result>) (Collection.x:273)
	at run() (CollectionBug.x:9)
	at ^collection_bug (CallLaterRequest: native)
```

**Comment by ggleyzer** [comment]
A simple workaround for now:

    module test {
        @Inject Console console;
    
        void run() {
            Callback[] callbacks = new Array();
            callbacks.add(new MyCallbackOne());
            callbacks.add(new MyCallbackTwo());
    
            val filtered = callbacks.filter(c -> !c.is(MyCallbackOne));
            for (Callback callback : filtered) {
                callback.call();
            }
        }
    
        interface Callback {
            void call();
        }
    
        const MyCallbackOne
                implements Callback {
            @Override
            void call() {
                console.print("one");
            }
        }
    
        const MyCallbackTwo
                implements Callback {
            @Override
            void call() {
                console.print("two");
            }
        }
    }

**Comment by ggleyzer** [comment]
Fixed by the change ["Bifurcate aggregator-related Collection API"](https://github.com/xtclang/xvm/commit/47a88d9537dc18c5d4925b81a38a0951041ad723) made on 8/16/23, 4:07 PM
